name: "BASE"
http:
  listenAddr: ":7070"
  debugAddr: ":7071"

grpc:
  listenAddr: ":11000"
  debugAddr: ":11001"

release:
  releaseVersion: "@RELEASE_VERSION@"
  releaseTime: "@RELEASE_TIME@"


database:
  url: root:123456@tcp(restless-db:3306)/?charset=utf8&parseTime=true
  maxIdle: 50
  maxActive: 100
  logMode: true

meta: "localhost:10000"
swaggerDir: "pb"