version: '3.7'

services:
  restless:
    build: .
    image: restless
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db
    command: ["./wait-for-it.sh","restless-db:3306", "--","./restless"]
  db:
    image: mysql:5.7
    container_name: 'restless-db'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      #      MYSQL_DATABASE: 'restless'
    ports:
      - '3306:3306'
#    volumes:
#      - restless-db:/var/lib/mysql
volumes:
  restless-db: