// Code generated by protoc-gen-go. DO NOT EDIT.
// source: newmeta/pb/meta.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/mazti/restless/shared/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateMetaRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMetaRequest) Reset()         { *m = CreateMetaRequest{} }
func (m *CreateMetaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMetaRequest) ProtoMessage()    {}
func (*CreateMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d8958bb9080931, []int{0}
}

func (m *CreateMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMetaRequest.Unmarshal(m, b)
}
func (m *CreateMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMetaRequest.Marshal(b, m, deterministic)
}
func (m *CreateMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMetaRequest.Merge(m, src)
}
func (m *CreateMetaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMetaRequest.Size(m)
}
func (m *CreateMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMetaRequest proto.InternalMessageInfo

func (m *CreateMetaRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

type CreateMetaReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base                 string   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Schema               string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMetaReply) Reset()         { *m = CreateMetaReply{} }
func (m *CreateMetaReply) String() string { return proto.CompactTextString(m) }
func (*CreateMetaReply) ProtoMessage()    {}
func (*CreateMetaReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d8958bb9080931, []int{1}
}

func (m *CreateMetaReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMetaReply.Unmarshal(m, b)
}
func (m *CreateMetaReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMetaReply.Marshal(b, m, deterministic)
}
func (m *CreateMetaReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMetaReply.Merge(m, src)
}
func (m *CreateMetaReply) XXX_Size() int {
	return xxx_messageInfo_CreateMetaReply.Size(m)
}
func (m *CreateMetaReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMetaReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMetaReply proto.InternalMessageInfo

func (m *CreateMetaReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateMetaReply) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *CreateMetaReply) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

type GetMetaReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base                 string   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Schema               string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetaReply) Reset()         { *m = GetMetaReply{} }
func (m *GetMetaReply) String() string { return proto.CompactTextString(m) }
func (*GetMetaReply) ProtoMessage()    {}
func (*GetMetaReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d8958bb9080931, []int{2}
}

func (m *GetMetaReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetaReply.Unmarshal(m, b)
}
func (m *GetMetaReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetaReply.Marshal(b, m, deterministic)
}
func (m *GetMetaReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaReply.Merge(m, src)
}
func (m *GetMetaReply) XXX_Size() int {
	return xxx_messageInfo_GetMetaReply.Size(m)
}
func (m *GetMetaReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaReply proto.InternalMessageInfo

func (m *GetMetaReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetMetaReply) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *GetMetaReply) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

type ListMetaReply struct {
	Metas                []*MetaModel         `protobuf:"bytes,1,rep,name=metas,proto3" json:"metas,omitempty"`
	Metadata             *proto1.ListMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListMetaReply) Reset()         { *m = ListMetaReply{} }
func (m *ListMetaReply) String() string { return proto.CompactTextString(m) }
func (*ListMetaReply) ProtoMessage()    {}
func (*ListMetaReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d8958bb9080931, []int{3}
}

func (m *ListMetaReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMetaReply.Unmarshal(m, b)
}
func (m *ListMetaReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMetaReply.Marshal(b, m, deterministic)
}
func (m *ListMetaReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMetaReply.Merge(m, src)
}
func (m *ListMetaReply) XXX_Size() int {
	return xxx_messageInfo_ListMetaReply.Size(m)
}
func (m *ListMetaReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMetaReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListMetaReply proto.InternalMessageInfo

func (m *ListMetaReply) GetMetas() []*MetaModel {
	if m != nil {
		return m.Metas
	}
	return nil
}

func (m *ListMetaReply) GetMetadata() *proto1.ListMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type UpdateMetaRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base                 string   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetaRequest) Reset()         { *m = UpdateMetaRequest{} }
func (m *UpdateMetaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMetaRequest) ProtoMessage()    {}
func (*UpdateMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d8958bb9080931, []int{4}
}

func (m *UpdateMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetaRequest.Unmarshal(m, b)
}
func (m *UpdateMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetaRequest.Merge(m, src)
}
func (m *UpdateMetaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMetaRequest.Size(m)
}
func (m *UpdateMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetaRequest proto.InternalMessageInfo

func (m *UpdateMetaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateMetaRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

type UpdateMetaReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base                 string   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Schema               string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetaReply) Reset()         { *m = UpdateMetaReply{} }
func (m *UpdateMetaReply) String() string { return proto.CompactTextString(m) }
func (*UpdateMetaReply) ProtoMessage()    {}
func (*UpdateMetaReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d8958bb9080931, []int{5}
}

func (m *UpdateMetaReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetaReply.Unmarshal(m, b)
}
func (m *UpdateMetaReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetaReply.Marshal(b, m, deterministic)
}
func (m *UpdateMetaReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetaReply.Merge(m, src)
}
func (m *UpdateMetaReply) XXX_Size() int {
	return xxx_messageInfo_UpdateMetaReply.Size(m)
}
func (m *UpdateMetaReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetaReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetaReply proto.InternalMessageInfo

func (m *UpdateMetaReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateMetaReply) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *UpdateMetaReply) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

type MetaModel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base                 string   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Schema               string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaModel) Reset()         { *m = MetaModel{} }
func (m *MetaModel) String() string { return proto.CompactTextString(m) }
func (*MetaModel) ProtoMessage()    {}
func (*MetaModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d8958bb9080931, []int{6}
}

func (m *MetaModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaModel.Unmarshal(m, b)
}
func (m *MetaModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaModel.Marshal(b, m, deterministic)
}
func (m *MetaModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaModel.Merge(m, src)
}
func (m *MetaModel) XXX_Size() int {
	return xxx_messageInfo_MetaModel.Size(m)
}
func (m *MetaModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaModel.DiscardUnknown(m)
}

var xxx_messageInfo_MetaModel proto.InternalMessageInfo

func (m *MetaModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MetaModel) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *MetaModel) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMetaRequest)(nil), "pb.CreateMetaRequest")
	proto.RegisterType((*CreateMetaReply)(nil), "pb.CreateMetaReply")
	proto.RegisterType((*GetMetaReply)(nil), "pb.GetMetaReply")
	proto.RegisterType((*ListMetaReply)(nil), "pb.ListMetaReply")
	proto.RegisterType((*UpdateMetaRequest)(nil), "pb.UpdateMetaRequest")
	proto.RegisterType((*UpdateMetaReply)(nil), "pb.UpdateMetaReply")
	proto.RegisterType((*MetaModel)(nil), "pb.MetaModel")
}

func init() { proto.RegisterFile("newmeta/pb/meta.proto", fileDescriptor_49d8958bb9080931) }

var fileDescriptor_49d8958bb9080931 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x15, 0x27, 0x35, 0x74, 0xda, 0xd0, 0x66, 0x4a, 0x50, 0x14, 0x71, 0xa8, 0x96, 0x03,
	0x55, 0x0f, 0x5e, 0x94, 0x1e, 0x90, 0x90, 0x10, 0x07, 0x28, 0x91, 0x80, 0x5c, 0x22, 0xf1, 0x00,
	0xeb, 0x7a, 0x70, 0x56, 0xb2, 0xbd, 0x8b, 0x77, 0x2b, 0x14, 0x10, 0x17, 0x5e, 0x81, 0x47, 0xe3,
	0x0d, 0x10, 0x0f, 0x82, 0x76, 0xd7, 0x4e, 0x4d, 0x7a, 0x41, 0x4a, 0x4f, 0xd9, 0x3f, 0x33, 0xbf,
	0xcc, 0xf7, 0x7d, 0x6b, 0x18, 0x57, 0xf4, 0xa5, 0x24, 0x2b, 0xb8, 0x4e, 0xb9, 0xfb, 0x4d, 0x74,
	0xad, 0xac, 0xc2, 0x48, 0xa7, 0xd3, 0xc7, 0xb9, 0x52, 0x79, 0x41, 0x5c, 0x68, 0xc9, 0x45, 0x55,
	0x29, 0x2b, 0xac, 0x54, 0x95, 0x09, 0x15, 0xd3, 0x8b, 0x5c, 0xda, 0xd5, 0x75, 0x9a, 0x5c, 0xa9,
	0x92, 0x97, 0xe2, 0xab, 0x95, 0xbc, 0x26, 0x63, 0x0b, 0x32, 0x86, 0x9b, 0x95, 0xa8, 0x29, 0xe3,
	0xbe, 0xae, 0xd9, 0x84, 0x26, 0xf6, 0x14, 0x46, 0xaf, 0x6b, 0x12, 0x96, 0x16, 0x64, 0xc5, 0x92,
	0x3e, 0x5f, 0x93, 0xb1, 0x88, 0x30, 0x48, 0x85, 0xa1, 0x49, 0xef, 0xb4, 0x77, 0xb6, 0xbf, 0xf4,
	0x6b, 0xb6, 0x80, 0xa3, 0x6e, 0xa1, 0x2e, 0xd6, 0xf8, 0x00, 0x22, 0x99, 0x35, 0x45, 0x91, 0xcc,
	0x36, 0x6d, 0xd1, 0x4d, 0x1b, 0x3e, 0x82, 0xd8, 0x5c, 0xad, 0xa8, 0x14, 0x93, 0xbe, 0x3f, 0x6d,
	0x76, 0xec, 0x1d, 0x1c, 0xce, 0xc9, 0xde, 0x0d, 0xeb, 0x13, 0x0c, 0x3f, 0x48, 0xd3, 0x81, 0x3d,
	0x81, 0x3d, 0xe7, 0x9c, 0x99, 0xf4, 0x4e, 0xfb, 0x67, 0x07, 0xb3, 0x61, 0xa2, 0xd3, 0xc4, 0xdd,
	0x2e, 0x54, 0x46, 0xc5, 0x32, 0xdc, 0xe1, 0x33, 0xb8, 0xef, 0x16, 0x99, 0xb0, 0xc2, 0xff, 0xcb,
	0xc1, 0xec, 0x61, 0xd2, 0x58, 0xd3, 0xd2, 0xdc, 0xdd, 0x72, 0x53, 0xc5, 0x9e, 0xc3, 0xe8, 0xa3,
	0xce, 0xb6, 0xbc, 0xfa, 0x8f, 0xc1, 0x9d, 0x77, 0xdd, 0xc6, 0x5d, 0xf5, 0xce, 0x61, 0x7f, 0xa3,
	0x66, 0x17, 0xd0, 0xec, 0x77, 0x04, 0x03, 0x47, 0xc2, 0xb7, 0x10, 0x87, 0x70, 0x71, 0xec, 0xbc,
	0xba, 0xf5, 0x22, 0xa6, 0x27, 0xdb, 0xc7, 0xba, 0x58, 0xb3, 0xe3, 0x1f, 0xbf, 0xfe, 0xfc, 0x8c,
	0x80, 0xed, 0xf9, 0x77, 0xfa, 0xa2, 0x77, 0x8e, 0xaf, 0xa0, 0x3f, 0x27, 0x8b, 0xd8, 0x1a, 0x39,
	0x27, 0xdb, 0x12, 0x8e, 0x1d, 0xa1, 0x1b, 0x39, 0x43, 0xdf, 0x7e, 0x88, 0xe0, 0xdb, 0xf9, 0x37,
	0x99, 0x7d, 0xc7, 0x97, 0x30, 0x70, 0xe6, 0xe3, 0x49, 0x37, 0x8a, 0x16, 0x31, 0x72, 0x88, 0x7f,
	0x92, 0x66, 0x43, 0xcf, 0xb8, 0x87, 0x61, 0x04, 0x7c, 0x0f, 0x71, 0x30, 0x3a, 0xe8, 0xb8, 0x95,
	0x56, 0xd0, 0xb1, 0x95, 0x05, 0x1b, 0x7b, 0xc8, 0xd1, 0xac, 0x33, 0x88, 0x13, 0x73, 0x09, 0xf1,
	0x1b, 0x2a, 0xc8, 0xc3, 0x9a, 0x69, 0xc2, 0xfe, 0x46, 0x52, 0x73, 0x7c, 0x59, 0x6a, 0xbb, 0x5e,
	0x98, 0xbc, 0x95, 0x74, 0xde, 0x21, 0xa5, 0xb1, 0xff, 0xd0, 0x2e, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xdd, 0x55, 0x5a, 0xd0, 0xd8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetaClient is the client API for Meta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaClient interface {
	Create(ctx context.Context, in *CreateMetaRequest, opts ...grpc.CallOption) (*CreateMetaReply, error)
	Get(ctx context.Context, in *proto1.GetRequest, opts ...grpc.CallOption) (*GetMetaReply, error)
	List(ctx context.Context, in *proto1.ListRequest, opts ...grpc.CallOption) (*ListMetaReply, error)
	Update(ctx context.Context, in *UpdateMetaRequest, opts ...grpc.CallOption) (*UpdateMetaReply, error)
	Delete(ctx context.Context, in *proto1.DeleteRequest, opts ...grpc.CallOption) (*proto1.EmptyMsg, error)
}

type metaClient struct {
	cc *grpc.ClientConn
}

func NewMetaClient(cc *grpc.ClientConn) MetaClient {
	return &metaClient{cc}
}

func (c *metaClient) Create(ctx context.Context, in *CreateMetaRequest, opts ...grpc.CallOption) (*CreateMetaReply, error) {
	out := new(CreateMetaReply)
	err := c.cc.Invoke(ctx, "/pb.Meta/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) Get(ctx context.Context, in *proto1.GetRequest, opts ...grpc.CallOption) (*GetMetaReply, error) {
	out := new(GetMetaReply)
	err := c.cc.Invoke(ctx, "/pb.Meta/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) List(ctx context.Context, in *proto1.ListRequest, opts ...grpc.CallOption) (*ListMetaReply, error) {
	out := new(ListMetaReply)
	err := c.cc.Invoke(ctx, "/pb.Meta/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) Update(ctx context.Context, in *UpdateMetaRequest, opts ...grpc.CallOption) (*UpdateMetaReply, error) {
	out := new(UpdateMetaReply)
	err := c.cc.Invoke(ctx, "/pb.Meta/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) Delete(ctx context.Context, in *proto1.DeleteRequest, opts ...grpc.CallOption) (*proto1.EmptyMsg, error) {
	out := new(proto1.EmptyMsg)
	err := c.cc.Invoke(ctx, "/pb.Meta/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServer is the server API for Meta service.
type MetaServer interface {
	Create(context.Context, *CreateMetaRequest) (*CreateMetaReply, error)
	Get(context.Context, *proto1.GetRequest) (*GetMetaReply, error)
	List(context.Context, *proto1.ListRequest) (*ListMetaReply, error)
	Update(context.Context, *UpdateMetaRequest) (*UpdateMetaReply, error)
	Delete(context.Context, *proto1.DeleteRequest) (*proto1.EmptyMsg, error)
}

// UnimplementedMetaServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServer struct {
}

func (*UnimplementedMetaServer) Create(ctx context.Context, req *CreateMetaRequest) (*CreateMetaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedMetaServer) Get(ctx context.Context, req *proto1.GetRequest) (*GetMetaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMetaServer) List(ctx context.Context, req *proto1.ListRequest) (*ListMetaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedMetaServer) Update(ctx context.Context, req *UpdateMetaRequest) (*UpdateMetaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedMetaServer) Delete(ctx context.Context, req *proto1.DeleteRequest) (*proto1.EmptyMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterMetaServer(s *grpc.Server, srv MetaServer) {
	s.RegisterService(&_Meta_serviceDesc, srv)
}

func _Meta_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Meta/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).Create(ctx, req.(*CreateMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Meta/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).Get(ctx, req.(*proto1.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Meta/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).List(ctx, req.(*proto1.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Meta/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).Update(ctx, req.(*UpdateMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Meta/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).Delete(ctx, req.(*proto1.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Meta_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Meta",
	HandlerType: (*MetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Meta_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Meta_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Meta_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Meta_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Meta_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "newmeta/pb/meta.proto",
}
