// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record/pb/record.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRecordsRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	MaxRecords           int32    `protobuf:"varint,3,opt,name=maxRecords,proto3" json:"maxRecords,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecordsRequest) Reset()         { *m = ListRecordsRequest{} }
func (m *ListRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequest) ProtoMessage()    {}
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{0}
}

func (m *ListRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequest.Unmarshal(m, b)
}
func (m *ListRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequest.Merge(m, src)
}
func (m *ListRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequest.Size(m)
}
func (m *ListRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequest proto.InternalMessageInfo

func (m *ListRecordsRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *ListRecordsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ListRecordsRequest) GetMaxRecords() int32 {
	if m != nil {
		return m.MaxRecords
	}
	return 0
}

func (m *ListRecordsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListRecordsReply struct {
	Offset               string       `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Records              []*RecordMsg `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListRecordsReply) Reset()         { *m = ListRecordsReply{} }
func (m *ListRecordsReply) String() string { return proto.CompactTextString(m) }
func (*ListRecordsReply) ProtoMessage()    {}
func (*ListRecordsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{1}
}

func (m *ListRecordsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsReply.Unmarshal(m, b)
}
func (m *ListRecordsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsReply.Marshal(b, m, deterministic)
}
func (m *ListRecordsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsReply.Merge(m, src)
}
func (m *ListRecordsReply) XXX_Size() int {
	return xxx_messageInfo_ListRecordsReply.Size(m)
}
func (m *ListRecordsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsReply proto.InternalMessageInfo

func (m *ListRecordsReply) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *ListRecordsReply) GetRecords() []*RecordMsg {
	if m != nil {
		return m.Records
	}
	return nil
}

type CreateRecordsRequest struct {
	Base                 string       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Table                string       `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Records              []*RecordMsg `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateRecordsRequest) Reset()         { *m = CreateRecordsRequest{} }
func (m *CreateRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecordsRequest) ProtoMessage()    {}
func (*CreateRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{2}
}

func (m *CreateRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordsRequest.Unmarshal(m, b)
}
func (m *CreateRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordsRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordsRequest.Merge(m, src)
}
func (m *CreateRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecordsRequest.Size(m)
}
func (m *CreateRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordsRequest proto.InternalMessageInfo

func (m *CreateRecordsRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *CreateRecordsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *CreateRecordsRequest) GetRecords() []*RecordMsg {
	if m != nil {
		return m.Records
	}
	return nil
}

type RecordMsg struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *_struct.Struct `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	CreatedTIme          string          `protobuf:"bytes,3,opt,name=createdTIme,proto3" json:"createdTIme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecordMsg) Reset()         { *m = RecordMsg{} }
func (m *RecordMsg) String() string { return proto.CompactTextString(m) }
func (*RecordMsg) ProtoMessage()    {}
func (*RecordMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{3}
}

func (m *RecordMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordMsg.Unmarshal(m, b)
}
func (m *RecordMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordMsg.Marshal(b, m, deterministic)
}
func (m *RecordMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordMsg.Merge(m, src)
}
func (m *RecordMsg) XXX_Size() int {
	return xxx_messageInfo_RecordMsg.Size(m)
}
func (m *RecordMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RecordMsg proto.InternalMessageInfo

func (m *RecordMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RecordMsg) GetFields() *_struct.Struct {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *RecordMsg) GetCreatedTIme() string {
	if m != nil {
		return m.CreatedTIme
	}
	return ""
}

type DeleteRecordsRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Records              []string `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordsRequest) Reset()         { *m = DeleteRecordsRequest{} }
func (m *DeleteRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordsRequest) ProtoMessage()    {}
func (*DeleteRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{4}
}

func (m *DeleteRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordsRequest.Unmarshal(m, b)
}
func (m *DeleteRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordsRequest.Merge(m, src)
}
func (m *DeleteRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordsRequest.Size(m)
}
func (m *DeleteRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordsRequest proto.InternalMessageInfo

func (m *DeleteRecordsRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *DeleteRecordsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DeleteRecordsRequest) GetRecords() []string {
	if m != nil {
		return m.Records
	}
	return nil
}

type DeleteRecordsReply struct {
	Records              []*DeleteRecordResult `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeleteRecordsReply) Reset()         { *m = DeleteRecordsReply{} }
func (m *DeleteRecordsReply) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordsReply) ProtoMessage()    {}
func (*DeleteRecordsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{5}
}

func (m *DeleteRecordsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordsReply.Unmarshal(m, b)
}
func (m *DeleteRecordsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordsReply.Marshal(b, m, deterministic)
}
func (m *DeleteRecordsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordsReply.Merge(m, src)
}
func (m *DeleteRecordsReply) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordsReply.Size(m)
}
func (m *DeleteRecordsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordsReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordsReply proto.InternalMessageInfo

func (m *DeleteRecordsReply) GetRecords() []*DeleteRecordResult {
	if m != nil {
		return m.Records
	}
	return nil
}

type DeleteRecordResult struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Deleted              bool     `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordResult) Reset()         { *m = DeleteRecordResult{} }
func (m *DeleteRecordResult) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordResult) ProtoMessage()    {}
func (*DeleteRecordResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{6}
}

func (m *DeleteRecordResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordResult.Unmarshal(m, b)
}
func (m *DeleteRecordResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordResult.Marshal(b, m, deterministic)
}
func (m *DeleteRecordResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordResult.Merge(m, src)
}
func (m *DeleteRecordResult) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordResult.Size(m)
}
func (m *DeleteRecordResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordResult proto.InternalMessageInfo

func (m *DeleteRecordResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteRecordResult) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type RetrievesRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	RecordID             string   `protobuf:"bytes,3,opt,name=recordID,proto3" json:"recordID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievesRequest) Reset()         { *m = RetrievesRequest{} }
func (m *RetrievesRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievesRequest) ProtoMessage()    {}
func (*RetrievesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{7}
}

func (m *RetrievesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievesRequest.Unmarshal(m, b)
}
func (m *RetrievesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievesRequest.Marshal(b, m, deterministic)
}
func (m *RetrievesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievesRequest.Merge(m, src)
}
func (m *RetrievesRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievesRequest.Size(m)
}
func (m *RetrievesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievesRequest proto.InternalMessageInfo

func (m *RetrievesRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *RetrievesRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *RetrievesRequest) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRecordsRequest)(nil), "pb.ListRecordsRequest")
	proto.RegisterType((*ListRecordsReply)(nil), "pb.ListRecordsReply")
	proto.RegisterType((*CreateRecordsRequest)(nil), "pb.CreateRecordsRequest")
	proto.RegisterType((*RecordMsg)(nil), "pb.RecordMsg")
	proto.RegisterType((*DeleteRecordsRequest)(nil), "pb.DeleteRecordsRequest")
	proto.RegisterType((*DeleteRecordsReply)(nil), "pb.DeleteRecordsReply")
	proto.RegisterType((*DeleteRecordResult)(nil), "pb.DeleteRecordResult")
	proto.RegisterType((*RetrievesRequest)(nil), "pb.RetrievesRequest")
}

func init() { proto.RegisterFile("record/pb/record.proto", fileDescriptor_9074497b9868df32) }

var fileDescriptor_9074497b9868df32 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0x9d, 0x36, 0x4d, 0x26, 0x4a, 0x7f, 0xfd, 0x8d, 0xac, 0xd4, 0xb2, 0x2a, 0x14, 0xf9,
	0x42, 0xd4, 0x83, 0x8d, 0xc2, 0x8d, 0x03, 0x17, 0x2a, 0xa4, 0x4a, 0x70, 0xd9, 0x14, 0x09, 0xca,
	0xc9, 0x8e, 0x27, 0xd1, 0x4a, 0x6e, 0xbc, 0x78, 0x37, 0x88, 0x36, 0xca, 0x85, 0x57, 0xe0, 0xc1,
	0x38, 0xf0, 0x0a, 0x3c, 0x08, 0xf2, 0xae, 0x9d, 0xd8, 0x49, 0xe0, 0xd0, 0xde, 0x3c, 0x7f, 0xfc,
	0x7d, 0xdf, 0xcc, 0x7c, 0x0b, 0x83, 0x9c, 0xa6, 0x59, 0x9e, 0x84, 0x22, 0x0e, 0xcd, 0x57, 0x20,
	0xf2, 0x4c, 0x65, 0x68, 0x8b, 0xd8, 0xbb, 0x98, 0x67, 0xd9, 0x3c, 0xa5, 0x30, 0x12, 0x3c, 0x8c,
	0x16, 0x8b, 0x4c, 0x45, 0x8a, 0x67, 0x0b, 0x69, 0x3a, 0x36, 0x55, 0x1d, 0xc5, 0xcb, 0x59, 0x28,
	0x55, 0xbe, 0x9c, 0x2a, 0x53, 0xf5, 0x1f, 0x00, 0xdf, 0x71, 0xa9, 0x98, 0xc6, 0x94, 0x8c, 0xbe,
	0x2c, 0x49, 0x2a, 0x44, 0x38, 0x8a, 0x23, 0x49, 0xae, 0x35, 0xb4, 0x46, 0x5d, 0xa6, 0xbf, 0xd1,
	0x81, 0x63, 0x15, 0xc5, 0x29, 0xb9, 0xb6, 0x4e, 0x9a, 0x00, 0x9f, 0x01, 0xdc, 0x45, 0xdf, 0xca,
	0xdf, 0xdd, 0xd6, 0xd0, 0x1a, 0x1d, 0xb3, 0x5a, 0x06, 0x3d, 0xe8, 0x88, 0x68, 0x4e, 0x13, 0xfe,
	0x40, 0xee, 0x91, 0xae, 0x6e, 0x62, 0x7f, 0x02, 0x67, 0x0d, 0x6e, 0x91, 0xde, 0xe3, 0x00, 0xda,
	0xd9, 0x6c, 0x26, 0x49, 0x95, 0xdc, 0x65, 0x84, 0xcf, 0xe1, 0x24, 0x2f, 0x49, 0xec, 0x61, 0x6b,
	0xd4, 0x1b, 0xf7, 0x03, 0x11, 0x07, 0xe6, 0xd7, 0xf7, 0x72, 0xce, 0xaa, 0xaa, 0xcf, 0xc1, 0x79,
	0x93, 0x53, 0xa4, 0xe8, 0xd1, 0x23, 0xd5, 0xa8, 0x5a, 0xff, 0xa4, 0x5a, 0x40, 0x77, 0x93, 0xc5,
	0x53, 0xb0, 0x79, 0x52, 0xa2, 0xdb, 0x3c, 0xc1, 0x10, 0xda, 0x33, 0x4e, 0xa9, 0xd6, 0x6b, 0x8d,
	0x7a, 0xe3, 0xf3, 0xc0, 0xdc, 0x21, 0xa8, 0xee, 0x10, 0x4c, 0xf4, 0x1d, 0x58, 0xd9, 0x86, 0x43,
	0xe8, 0x4d, 0xb5, 0xf0, 0xe4, 0xe6, 0xfa, 0x8e, 0xf4, 0x2a, 0xbb, 0xac, 0x9e, 0xf2, 0x6f, 0xc1,
	0xb9, 0xa2, 0x94, 0x9e, 0x30, 0x9a, 0xdb, 0x1c, 0xad, 0xbb, 0x9d, 0xe5, 0x2d, 0xe0, 0x0e, 0x76,
	0x71, 0x8d, 0x17, 0xdb, 0x7e, 0x4b, 0xaf, 0x62, 0x50, 0xac, 0xa2, 0xde, 0xc8, 0x48, 0x2e, 0x53,
	0xb5, 0xc5, 0x79, 0xdd, 0xc4, 0x31, 0xe5, 0xbd, 0xe5, 0xb8, 0x70, 0x92, 0xe8, 0xae, 0x44, 0xeb,
	0xeb, 0xb0, 0x2a, 0xf4, 0x3f, 0xc2, 0x19, 0x23, 0x95, 0x73, 0xfa, 0x4a, 0x8f, 0x98, 0xcf, 0x83,
	0x8e, 0x11, 0x72, 0x7d, 0x55, 0x2e, 0x70, 0x13, 0x8f, 0x7f, 0xb6, 0xa0, 0x6d, 0x44, 0xe1, 0x0d,
	0xf4, 0x6a, 0xc6, 0x43, 0x3d, 0xd4, 0xfe, 0x2b, 0xf0, 0x9c, 0xbd, 0xbc, 0x48, 0xef, 0xfd, 0xf3,
	0xef, 0xbf, 0x7e, 0xff, 0xb0, 0xff, 0xc7, 0xff, 0xc2, 0x55, 0xa1, 0x64, 0x1d, 0xae, 0x34, 0xf7,
	0x1a, 0x3f, 0xc1, 0x69, 0x25, 0xbd, 0xe4, 0x71, 0x8c, 0x71, 0x9a, 0xe3, 0x78, 0x4d, 0x3b, 0xf9,
	0xbe, 0xc6, 0xbb, 0x40, 0x6f, 0x07, 0x2f, 0x5c, 0x55, 0xd2, 0xd7, 0xf8, 0x19, 0xfa, 0x0d, 0x53,
	0xa3, 0x5b, 0x60, 0x1c, 0xf2, 0xf9, 0x5f, 0x44, 0x7b, 0x9a, 0xc4, 0xf1, 0x77, 0x45, 0xbf, 0xb2,
	0x2e, 0x0b, 0xf0, 0x0f, 0x22, 0x79, 0x3a, 0xf8, 0xf8, 0x10, 0xf8, 0x2d, 0xf4, 0x1b, 0xbe, 0x32,
	0xe0, 0x87, 0x6c, 0xec, 0x0d, 0x0e, 0x54, 0x6a, 0x0b, 0xbf, 0xdc, 0x85, 0x8f, 0xdb, 0xfa, 0x29,
	0xbd, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x41, 0x59, 0x0a, 0x1c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordClient is the client API for Record service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordClient interface {
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error)
	RetrieveRecord(ctx context.Context, in *RetrievesRequest, opts ...grpc.CallOption) (*RecordMsg, error)
	CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error)
	UpdateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error)
	DeleteRecords(ctx context.Context, in *DeleteRecordsRequest, opts ...grpc.CallOption) (*DeleteRecordsReply, error)
}

type recordClient struct {
	cc *grpc.ClientConn
}

func NewRecordClient(cc *grpc.ClientConn) RecordClient {
	return &recordClient{cc}
}

func (c *recordClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error) {
	out := new(ListRecordsReply)
	err := c.cc.Invoke(ctx, "/pb.Record/ListRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) RetrieveRecord(ctx context.Context, in *RetrievesRequest, opts ...grpc.CallOption) (*RecordMsg, error) {
	out := new(RecordMsg)
	err := c.cc.Invoke(ctx, "/pb.Record/RetrieveRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error) {
	out := new(ListRecordsReply)
	err := c.cc.Invoke(ctx, "/pb.Record/CreateRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) UpdateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error) {
	out := new(ListRecordsReply)
	err := c.cc.Invoke(ctx, "/pb.Record/UpdateRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) DeleteRecords(ctx context.Context, in *DeleteRecordsRequest, opts ...grpc.CallOption) (*DeleteRecordsReply, error) {
	out := new(DeleteRecordsReply)
	err := c.cc.Invoke(ctx, "/pb.Record/DeleteRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServer is the server API for Record service.
type RecordServer interface {
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsReply, error)
	RetrieveRecord(context.Context, *RetrievesRequest) (*RecordMsg, error)
	CreateRecords(context.Context, *CreateRecordsRequest) (*ListRecordsReply, error)
	UpdateRecords(context.Context, *CreateRecordsRequest) (*ListRecordsReply, error)
	DeleteRecords(context.Context, *DeleteRecordsRequest) (*DeleteRecordsReply, error)
}

// UnimplementedRecordServer can be embedded to have forward compatible implementations.
type UnimplementedRecordServer struct {
}

func (*UnimplementedRecordServer) ListRecords(ctx context.Context, req *ListRecordsRequest) (*ListRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecords not implemented")
}
func (*UnimplementedRecordServer) RetrieveRecord(ctx context.Context, req *RetrievesRequest) (*RecordMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveRecord not implemented")
}
func (*UnimplementedRecordServer) CreateRecords(ctx context.Context, req *CreateRecordsRequest) (*ListRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecords not implemented")
}
func (*UnimplementedRecordServer) UpdateRecords(ctx context.Context, req *CreateRecordsRequest) (*ListRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRecords not implemented")
}
func (*UnimplementedRecordServer) DeleteRecords(ctx context.Context, req *DeleteRecordsRequest) (*DeleteRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecords not implemented")
}

func RegisterRecordServer(s *grpc.Server, srv RecordServer) {
	s.RegisterService(&_Record_serviceDesc, srv)
}

func _Record_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/ListRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_RetrieveRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).RetrieveRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/RetrieveRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).RetrieveRecord(ctx, req.(*RetrievesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_CreateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).CreateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/CreateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).CreateRecords(ctx, req.(*CreateRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_UpdateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).UpdateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/UpdateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).UpdateRecords(ctx, req.(*CreateRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_DeleteRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).DeleteRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/DeleteRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).DeleteRecords(ctx, req.(*DeleteRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Record_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Record",
	HandlerType: (*RecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRecords",
			Handler:    _Record_ListRecords_Handler,
		},
		{
			MethodName: "RetrieveRecord",
			Handler:    _Record_RetrieveRecord_Handler,
		},
		{
			MethodName: "CreateRecords",
			Handler:    _Record_CreateRecords_Handler,
		},
		{
			MethodName: "UpdateRecords",
			Handler:    _Record_UpdateRecords_Handler,
		},
		{
			MethodName: "DeleteRecords",
			Handler:    _Record_DeleteRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "record/pb/record.proto",
}
