// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record/pb/record.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRecordsRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	MaxRecords           int32    `protobuf:"varint,3,opt,name=maxRecords,proto3" json:"maxRecords,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecordsRequest) Reset()         { *m = ListRecordsRequest{} }
func (m *ListRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequest) ProtoMessage()    {}
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{0}
}

func (m *ListRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequest.Unmarshal(m, b)
}
func (m *ListRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequest.Merge(m, src)
}
func (m *ListRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequest.Size(m)
}
func (m *ListRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequest proto.InternalMessageInfo

func (m *ListRecordsRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *ListRecordsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ListRecordsRequest) GetMaxRecords() int32 {
	if m != nil {
		return m.MaxRecords
	}
	return 0
}

func (m *ListRecordsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListRecordsReply struct {
	Offset               string       `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Records              []*RecordMsg `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListRecordsReply) Reset()         { *m = ListRecordsReply{} }
func (m *ListRecordsReply) String() string { return proto.CompactTextString(m) }
func (*ListRecordsReply) ProtoMessage()    {}
func (*ListRecordsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{1}
}

func (m *ListRecordsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsReply.Unmarshal(m, b)
}
func (m *ListRecordsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsReply.Marshal(b, m, deterministic)
}
func (m *ListRecordsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsReply.Merge(m, src)
}
func (m *ListRecordsReply) XXX_Size() int {
	return xxx_messageInfo_ListRecordsReply.Size(m)
}
func (m *ListRecordsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsReply proto.InternalMessageInfo

func (m *ListRecordsReply) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *ListRecordsReply) GetRecords() []*RecordMsg {
	if m != nil {
		return m.Records
	}
	return nil
}

type CreateRecordsRequest struct {
	Base                 string       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Table                string       `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Records              []*RecordMsg `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateRecordsRequest) Reset()         { *m = CreateRecordsRequest{} }
func (m *CreateRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecordsRequest) ProtoMessage()    {}
func (*CreateRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{2}
}

func (m *CreateRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordsRequest.Unmarshal(m, b)
}
func (m *CreateRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordsRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordsRequest.Merge(m, src)
}
func (m *CreateRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecordsRequest.Size(m)
}
func (m *CreateRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordsRequest proto.InternalMessageInfo

func (m *CreateRecordsRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *CreateRecordsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *CreateRecordsRequest) GetRecords() []*RecordMsg {
	if m != nil {
		return m.Records
	}
	return nil
}

type RecordMsg struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *_struct.Struct `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecordMsg) Reset()         { *m = RecordMsg{} }
func (m *RecordMsg) String() string { return proto.CompactTextString(m) }
func (*RecordMsg) ProtoMessage()    {}
func (*RecordMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{3}
}

func (m *RecordMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordMsg.Unmarshal(m, b)
}
func (m *RecordMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordMsg.Marshal(b, m, deterministic)
}
func (m *RecordMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordMsg.Merge(m, src)
}
func (m *RecordMsg) XXX_Size() int {
	return xxx_messageInfo_RecordMsg.Size(m)
}
func (m *RecordMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RecordMsg proto.InternalMessageInfo

func (m *RecordMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RecordMsg) GetFields() *_struct.Struct {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRecordsRequest)(nil), "pb.ListRecordsRequest")
	proto.RegisterType((*ListRecordsReply)(nil), "pb.ListRecordsReply")
	proto.RegisterType((*CreateRecordsRequest)(nil), "pb.CreateRecordsRequest")
	proto.RegisterType((*RecordMsg)(nil), "pb.RecordMsg")
}

func init() { proto.RegisterFile("record/pb/record.proto", fileDescriptor_9074497b9868df32) }

var fileDescriptor_9074497b9868df32 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x4d, 0x0b, 0xf4, 0x3d, 0x2e, 0xe1, 0x3d, 0xbd, 0x69, 0xa0, 0x69, 0x8c, 0x21, 0xdd, 0xd8,
	0xb8, 0xe8, 0x24, 0xb8, 0x73, 0xeb, 0x16, 0x37, 0xc5, 0x9d, 0xab, 0x29, 0x4c, 0x9b, 0x49, 0x2a,
	0x33, 0x76, 0x86, 0x44, 0x20, 0x6c, 0xfc, 0x05, 0x3f, 0xc7, 0xcf, 0xf0, 0x17, 0xfc, 0x10, 0xc3,
	0x4c, 0x21, 0x20, 0xea, 0xc2, 0xdd, 0xdc, 0x7b, 0xee, 0x3d, 0x67, 0xce, 0x3d, 0xd0, 0xab, 0xd8,
	0x44, 0x54, 0x53, 0x22, 0x33, 0x62, 0x5f, 0x89, 0xac, 0x84, 0x16, 0xe8, 0xca, 0x2c, 0x3c, 0x2b,
	0x84, 0x28, 0x4a, 0x46, 0xa8, 0xe4, 0x84, 0xce, 0x66, 0x42, 0x53, 0xcd, 0xc5, 0x4c, 0xd9, 0x89,
	0x1d, 0x6a, 0xaa, 0x6c, 0x9e, 0x13, 0xa5, 0xab, 0xf9, 0x44, 0x5b, 0x34, 0x5a, 0x02, 0x8e, 0xb8,
	0xd2, 0xa9, 0xe1, 0x54, 0x29, 0x7b, 0x9c, 0x33, 0xa5, 0x11, 0xa1, 0x99, 0x51, 0xc5, 0x02, 0x67,
	0xe0, 0xc4, 0xed, 0xd4, 0xbc, 0xd1, 0x87, 0x96, 0xa6, 0x59, 0xc9, 0x02, 0xd7, 0x34, 0x6d, 0x81,
	0xe7, 0x00, 0x0f, 0xf4, 0xa9, 0x5e, 0x0f, 0x1a, 0x03, 0x27, 0x6e, 0xa5, 0x7b, 0x1d, 0x0c, 0xe1,
	0xaf, 0xa4, 0x05, 0x1b, 0xf3, 0x25, 0x0b, 0x9a, 0x06, 0xdd, 0xd5, 0xd1, 0x18, 0x4e, 0x0e, 0xb4,
	0x65, 0xb9, 0xc0, 0x1e, 0x78, 0x22, 0xcf, 0x15, 0xd3, 0xb5, 0x76, 0x5d, 0xe1, 0x05, 0xfc, 0xa9,
	0x6a, 0x11, 0x77, 0xd0, 0x88, 0x3b, 0xc3, 0x6e, 0x22, 0xb3, 0xc4, 0xae, 0xde, 0xaa, 0x22, 0xdd,
	0xa2, 0x11, 0x07, 0xff, 0xa6, 0x62, 0x54, 0xb3, 0x5f, 0x5b, 0xda, 0x93, 0x6a, 0xfc, 0x28, 0x35,
	0x82, 0xf6, 0xae, 0x8b, 0xff, 0xc0, 0xe5, 0xd3, 0x9a, 0xdd, 0xe5, 0x53, 0x24, 0xe0, 0xe5, 0x9c,
	0x95, 0xe6, 0xbf, 0x4e, 0xdc, 0x19, 0xf6, 0x13, 0x9b, 0x43, 0xb2, 0xcd, 0x21, 0x19, 0x9b, 0x1c,
	0xd2, 0x7a, 0x6c, 0xf8, 0xea, 0x80, 0x67, 0xe9, 0xf0, 0x0e, 0x3a, 0x7b, 0x87, 0xc1, 0xde, 0x46,
	0xff, 0x38, 0xa5, 0xd0, 0x3f, 0xea, 0xcb, 0x72, 0x11, 0xf5, 0x9f, 0xdf, 0xde, 0x5f, 0xdc, 0x53,
	0xfc, 0x4f, 0x56, 0x1b, 0x93, 0x6b, 0xb2, 0x32, 0xb6, 0xd6, 0x78, 0x0f, 0xdd, 0x83, 0xcb, 0x60,
	0xb0, 0xd9, 0xff, 0xea, 0x58, 0xdf, 0x30, 0x87, 0x86, 0xd9, 0x8f, 0x3e, 0x33, 0x5f, 0x3b, 0x97,
	0x99, 0x67, 0x6c, 0x5d, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x27, 0x8d, 0x28, 0xa8, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordClient is the client API for Record service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordClient interface {
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error)
	CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error)
}

type recordClient struct {
	cc *grpc.ClientConn
}

func NewRecordClient(cc *grpc.ClientConn) RecordClient {
	return &recordClient{cc}
}

func (c *recordClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error) {
	out := new(ListRecordsReply)
	err := c.cc.Invoke(ctx, "/pb.Record/ListRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error) {
	out := new(ListRecordsReply)
	err := c.cc.Invoke(ctx, "/pb.Record/CreateRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServer is the server API for Record service.
type RecordServer interface {
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsReply, error)
	CreateRecords(context.Context, *CreateRecordsRequest) (*ListRecordsReply, error)
}

// UnimplementedRecordServer can be embedded to have forward compatible implementations.
type UnimplementedRecordServer struct {
}

func (*UnimplementedRecordServer) ListRecords(ctx context.Context, req *ListRecordsRequest) (*ListRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecords not implemented")
}
func (*UnimplementedRecordServer) CreateRecords(ctx context.Context, req *CreateRecordsRequest) (*ListRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecords not implemented")
}

func RegisterRecordServer(s *grpc.Server, srv RecordServer) {
	s.RegisterService(&_Record_serviceDesc, srv)
}

func _Record_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/ListRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_CreateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).CreateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/CreateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).CreateRecords(ctx, req.(*CreateRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Record_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Record",
	HandlerType: (*RecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRecords",
			Handler:    _Record_ListRecords_Handler,
		},
		{
			MethodName: "CreateRecords",
			Handler:    _Record_CreateRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "record/pb/record.proto",
}
