// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// MetaSchema is the predicate function for metaschema builders.
type MetaSchema func(*sql.Selector)
