// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/mazti/restless/base/ent/migrate"

	"github.com/mazti/restless/base/ent/metaschema"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MetaSchema is the client for interacting with the MetaSchema builders.
	MetaSchema *MetaSchemaClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	c := config{log: log.Println}
	c.options(opts...)
	return &Client{
		config:     c,
		Schema:     migrate.NewSchema(c.driver),
		MetaSchema: NewMetaSchemaClient(c),
	}
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug}
	return &Tx{
		config:     cfg,
		MetaSchema: NewMetaSchemaClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MetaSchema.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true}
	return &Client{
		config:     cfg,
		Schema:     migrate.NewSchema(cfg.driver),
		MetaSchema: NewMetaSchemaClient(cfg),
	}
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// MetaSchemaClient is a client for the MetaSchema schema.
type MetaSchemaClient struct {
	config
}

// NewMetaSchemaClient returns a client for the MetaSchema from the given config.
func NewMetaSchemaClient(c config) *MetaSchemaClient {
	return &MetaSchemaClient{config: c}
}

// Create returns a create builder for MetaSchema.
func (c *MetaSchemaClient) Create() *MetaSchemaCreate {
	return &MetaSchemaCreate{config: c.config}
}

// Update returns an update builder for MetaSchema.
func (c *MetaSchemaClient) Update() *MetaSchemaUpdate {
	return &MetaSchemaUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *MetaSchemaClient) UpdateOne(ms *MetaSchema) *MetaSchemaUpdateOne {
	return c.UpdateOneID(ms.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *MetaSchemaClient) UpdateOneID(id int) *MetaSchemaUpdateOne {
	return &MetaSchemaUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for MetaSchema.
func (c *MetaSchemaClient) Delete() *MetaSchemaDelete {
	return &MetaSchemaDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MetaSchemaClient) DeleteOne(ms *MetaSchema) *MetaSchemaDeleteOne {
	return c.DeleteOneID(ms.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MetaSchemaClient) DeleteOneID(id int) *MetaSchemaDeleteOne {
	return &MetaSchemaDeleteOne{c.Delete().Where(metaschema.ID(id))}
}

// Create returns a query builder for MetaSchema.
func (c *MetaSchemaClient) Query() *MetaSchemaQuery {
	return &MetaSchemaQuery{config: c.config}
}

// Get returns a MetaSchema entity by its id.
func (c *MetaSchemaClient) Get(ctx context.Context, id int) (*MetaSchema, error) {
	return c.Query().Where(metaschema.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MetaSchemaClient) GetX(ctx context.Context, id int) *MetaSchema {
	ms, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return ms
}
