// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dto "github.com/mazti/restless/base/dto"
	mock "github.com/stretchr/testify/mock"
)

// BaseRepository is an autogenerated mock type for the BaseRepository type
type BaseRepository struct {
	mock.Mock
}

// CreateSchema provides a mock function with given fields: name
func (_m *BaseRepository) CreateSchema(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTable provides a mock function with given fields: base
func (_m *BaseRepository) CreateTable(base dto.CreateTableReq) error {
	ret := _m.Called(base)

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.CreateTableReq) error); ok {
		r0 = rf(base)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
