// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	ent "github.com/mazti/restless/base/ent"
	mock "github.com/stretchr/testify/mock"
)

// MetaTableRepository is an autogenerated mock type for the MetaTableRepository type
type MetaTableRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *MetaTableRepository) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, schemaId, table
func (_m *MetaTableRepository) Create(ctx context.Context, schemaId int, table ent.MetaTable) (*ent.MetaTable, error) {
	ret := _m.Called(ctx, schemaId, table)

	var r0 *ent.MetaTable
	if rf, ok := ret.Get(0).(func(context.Context, int, ent.MetaTable) *ent.MetaTable); ok {
		r0 = rf(ctx, schemaId, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.MetaTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, ent.MetaTable) error); ok {
		r1 = rf(ctx, schemaId, table)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MetaTableRepository) Delete(ctx context.Context, id int) (*ent.MetaTable, error) {
	ret := _m.Called(ctx, id)

	var r0 *ent.MetaTable
	if rf, ok := ret.Get(0).(func(context.Context, int) *ent.MetaTable); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.MetaTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *MetaTableRepository) Get(ctx context.Context, id int) (*ent.MetaTable, error) {
	ret := _m.Called(ctx, id)

	var r0 *ent.MetaTable
	if rf, ok := ret.Get(0).(func(context.Context, int) *ent.MetaTable); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.MetaTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MetaTableRepository) List(ctx context.Context, offset int, limit int) ([]*ent.MetaTable, error) {
	ret := _m.Called(ctx, offset, limit)

	var r0 []*ent.MetaTable
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*ent.MetaTable); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.MetaTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, table
func (_m *MetaTableRepository) Update(ctx context.Context, table ent.MetaTable) (*ent.MetaTable, error) {
	ret := _m.Called(ctx, table)

	var r0 *ent.MetaTable
	if rf, ok := ret.Get(0).(func(context.Context, ent.MetaTable) *ent.MetaTable); ok {
		r0 = rf(ctx, table)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.MetaTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ent.MetaTable) error); ok {
		r1 = rf(ctx, table)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
