// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/pb/base.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/mazti/restless/shared/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBaseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBaseRequest) Reset()         { *m = CreateBaseRequest{} }
func (m *CreateBaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBaseRequest) ProtoMessage()    {}
func (*CreateBaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{0}
}

func (m *CreateBaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBaseRequest.Unmarshal(m, b)
}
func (m *CreateBaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBaseRequest.Marshal(b, m, deterministic)
}
func (m *CreateBaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBaseRequest.Merge(m, src)
}
func (m *CreateBaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBaseRequest.Size(m)
}
func (m *CreateBaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBaseRequest proto.InternalMessageInfo

func (m *CreateBaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateBaseReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBaseReply) Reset()         { *m = CreateBaseReply{} }
func (m *CreateBaseReply) String() string { return proto.CompactTextString(m) }
func (*CreateBaseReply) ProtoMessage()    {}
func (*CreateBaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{1}
}

func (m *CreateBaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBaseReply.Unmarshal(m, b)
}
func (m *CreateBaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBaseReply.Marshal(b, m, deterministic)
}
func (m *CreateBaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBaseReply.Merge(m, src)
}
func (m *CreateBaseReply) XXX_Size() int {
	return xxx_messageInfo_CreateBaseReply.Size(m)
}
func (m *CreateBaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBaseReply proto.InternalMessageInfo

func (m *CreateBaseReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateBaseReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBaseReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBaseReply) Reset()         { *m = GetBaseReply{} }
func (m *GetBaseReply) String() string { return proto.CompactTextString(m) }
func (*GetBaseReply) ProtoMessage()    {}
func (*GetBaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{2}
}

func (m *GetBaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBaseReply.Unmarshal(m, b)
}
func (m *GetBaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBaseReply.Marshal(b, m, deterministic)
}
func (m *GetBaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBaseReply.Merge(m, src)
}
func (m *GetBaseReply) XXX_Size() int {
	return xxx_messageInfo_GetBaseReply.Size(m)
}
func (m *GetBaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBaseReply proto.InternalMessageInfo

func (m *GetBaseReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetBaseReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListBaseReply struct {
	Bases                []*BaseModel         `protobuf:"bytes,1,rep,name=bases,proto3" json:"bases,omitempty"`
	Metadata             *proto1.ListMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListBaseReply) Reset()         { *m = ListBaseReply{} }
func (m *ListBaseReply) String() string { return proto.CompactTextString(m) }
func (*ListBaseReply) ProtoMessage()    {}
func (*ListBaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{3}
}

func (m *ListBaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBaseReply.Unmarshal(m, b)
}
func (m *ListBaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBaseReply.Marshal(b, m, deterministic)
}
func (m *ListBaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBaseReply.Merge(m, src)
}
func (m *ListBaseReply) XXX_Size() int {
	return xxx_messageInfo_ListBaseReply.Size(m)
}
func (m *ListBaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListBaseReply proto.InternalMessageInfo

func (m *ListBaseReply) GetBases() []*BaseModel {
	if m != nil {
		return m.Bases
	}
	return nil
}

func (m *ListBaseReply) GetMetadata() *proto1.ListMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type UpdateBaseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBaseRequest) Reset()         { *m = UpdateBaseRequest{} }
func (m *UpdateBaseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBaseRequest) ProtoMessage()    {}
func (*UpdateBaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{4}
}

func (m *UpdateBaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBaseRequest.Unmarshal(m, b)
}
func (m *UpdateBaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBaseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBaseRequest.Merge(m, src)
}
func (m *UpdateBaseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBaseRequest.Size(m)
}
func (m *UpdateBaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBaseRequest proto.InternalMessageInfo

func (m *UpdateBaseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateBaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateBaseReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBaseReply) Reset()         { *m = UpdateBaseReply{} }
func (m *UpdateBaseReply) String() string { return proto.CompactTextString(m) }
func (*UpdateBaseReply) ProtoMessage()    {}
func (*UpdateBaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{5}
}

func (m *UpdateBaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBaseReply.Unmarshal(m, b)
}
func (m *UpdateBaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBaseReply.Marshal(b, m, deterministic)
}
func (m *UpdateBaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBaseReply.Merge(m, src)
}
func (m *UpdateBaseReply) XXX_Size() int {
	return xxx_messageInfo_UpdateBaseReply.Size(m)
}
func (m *UpdateBaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBaseReply proto.InternalMessageInfo

func (m *UpdateBaseReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateBaseReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BaseModel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseModel) Reset()         { *m = BaseModel{} }
func (m *BaseModel) String() string { return proto.CompactTextString(m) }
func (*BaseModel) ProtoMessage()    {}
func (*BaseModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{6}
}

func (m *BaseModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseModel.Unmarshal(m, b)
}
func (m *BaseModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseModel.Marshal(b, m, deterministic)
}
func (m *BaseModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseModel.Merge(m, src)
}
func (m *BaseModel) XXX_Size() int {
	return xxx_messageInfo_BaseModel.Size(m)
}
func (m *BaseModel) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseModel.DiscardUnknown(m)
}

var xxx_messageInfo_BaseModel proto.InternalMessageInfo

func (m *BaseModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BaseModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBaseRequest)(nil), "pb.CreateBaseRequest")
	proto.RegisterType((*CreateBaseReply)(nil), "pb.CreateBaseReply")
	proto.RegisterType((*GetBaseReply)(nil), "pb.GetBaseReply")
	proto.RegisterType((*ListBaseReply)(nil), "pb.ListBaseReply")
	proto.RegisterType((*UpdateBaseRequest)(nil), "pb.UpdateBaseRequest")
	proto.RegisterType((*UpdateBaseReply)(nil), "pb.UpdateBaseReply")
	proto.RegisterType((*BaseModel)(nil), "pb.BaseModel")
}

func init() { proto.RegisterFile("base/pb/base.proto", fileDescriptor_0d99073f0a37c125) }

var fileDescriptor_0d99073f0a37c125 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x15, 0x37, 0x0d, 0x74, 0xda, 0x90, 0x66, 0x4a, 0xa5, 0x2a, 0xe2, 0x50, 0x2d, 0x07,
	0xaa, 0x1e, 0xbc, 0x60, 0xa8, 0x22, 0x21, 0x21, 0x24, 0xa0, 0xe4, 0x00, 0xb9, 0x44, 0xe2, 0x01,
	0xd6, 0x78, 0x48, 0x57, 0xb2, 0xbd, 0x8b, 0x77, 0x8b, 0x14, 0x21, 0x2e, 0xbc, 0x02, 0x8f, 0xc6,
	0x1b, 0x20, 0x1e, 0x04, 0xed, 0xae, 0x1d, 0x96, 0xe4, 0x12, 0x4e, 0xf6, 0xee, 0xcc, 0xff, 0x69,
	0xfe, 0x7f, 0x6c, 0xc0, 0x5c, 0x18, 0xe2, 0x3a, 0xe7, 0xee, 0x99, 0xea, 0x46, 0x59, 0x85, 0x89,
	0xce, 0x27, 0x0f, 0x96, 0x4a, 0x2d, 0x4b, 0xe2, 0x42, 0x4b, 0x2e, 0xea, 0x5a, 0x59, 0x61, 0xa5,
	0xaa, 0x4d, 0xe8, 0x98, 0x4c, 0x97, 0xd2, 0xde, 0xdc, 0xe6, 0xe9, 0x47, 0x55, 0x71, 0x2b, 0xa9,
	0xae, 0xbf, 0x3c, 0x79, 0x36, 0xe5, 0x0d, 0x19, 0x5b, 0x92, 0x31, 0xdc, 0xdc, 0x88, 0x86, 0x0a,
	0xee, 0x7b, 0xdb, 0x43, 0x10, 0xb2, 0x47, 0x30, 0x7e, 0xdd, 0x90, 0xb0, 0xf4, 0x4a, 0x18, 0x5a,
	0xd0, 0xe7, 0x5b, 0x32, 0x16, 0x11, 0xfa, 0xb5, 0xa8, 0xe8, 0xac, 0x77, 0xde, 0xbb, 0x38, 0x58,
	0xf8, 0x77, 0x76, 0x05, 0xa3, 0xb8, 0x51, 0x97, 0x2b, 0xbc, 0x07, 0x89, 0x2c, 0xda, 0xa6, 0x44,
	0x16, 0x6b, 0x59, 0x12, 0xc9, 0x32, 0x38, 0x9a, 0x91, 0xfd, 0x3f, 0xcd, 0x27, 0x18, 0xbe, 0x97,
	0x26, 0x12, 0x3d, 0x84, 0x7d, 0x97, 0x86, 0x39, 0xeb, 0x9d, 0xef, 0x5d, 0x1c, 0x66, 0xc3, 0x54,
	0xe7, 0xa9, 0xab, 0xce, 0x55, 0x41, 0xe5, 0x22, 0xd4, 0xf0, 0x31, 0xdc, 0xad, 0xc8, 0x8a, 0x42,
	0x58, 0xe1, 0x69, 0x87, 0xd9, 0xfd, 0xb4, 0xb5, 0xea, 0x68, 0xf3, 0xb6, 0xb6, 0x58, 0x77, 0xb1,
	0x29, 0x8c, 0x3f, 0xe8, 0x62, 0xc3, 0xfb, 0x2e, 0x03, 0x5e, 0xc1, 0x28, 0x16, 0xee, 0xea, 0x8b,
	0xc3, 0xc1, 0x7a, 0xea, 0x5d, 0x04, 0xd9, 0xaf, 0x04, 0xfa, 0x4e, 0x81, 0x6f, 0x61, 0x10, 0xc2,
	0xc7, 0x53, 0xe7, 0x7d, 0x6b, 0x63, 0x93, 0x93, 0xcd, 0x6b, 0x5d, 0xae, 0xd8, 0xf1, 0xf7, 0x9f,
	0xbf, 0x7f, 0x24, 0xc0, 0xf6, 0xfd, 0xb7, 0xf4, 0xbc, 0x77, 0x89, 0x2f, 0x61, 0x6f, 0x46, 0x16,
	0xb1, 0x0b, 0x66, 0x46, 0xb6, 0x23, 0x1c, 0x3b, 0x42, 0xbc, 0x2a, 0x86, 0x5e, 0x7e, 0x84, 0xe0,
	0xe5, 0xfc, 0xab, 0x2c, 0xbe, 0xe1, 0x0b, 0xe8, 0xbb, 0x30, 0xf1, 0x24, 0x8e, 0xb6, 0x43, 0x8c,
	0x1d, 0xe2, 0x9f, 0xcd, 0xb1, 0xa1, 0x67, 0xdc, 0xc1, 0x30, 0x02, 0xbe, 0x83, 0x41, 0x08, 0x2e,
	0xf8, 0xd8, 0x4a, 0x3f, 0xf8, 0xd8, 0xc8, 0x96, 0x9d, 0x7a, 0xc8, 0x28, 0x8b, 0x06, 0x71, 0x66,
	0xae, 0x61, 0xf0, 0x86, 0x4a, 0xf2, 0xb0, 0x76, 0x9a, 0x70, 0xfe, 0x6b, 0xa9, 0xbd, 0xbe, 0xae,
	0xb4, 0x5d, 0xcd, 0xcd, 0xb2, 0xb3, 0x74, 0x19, 0x91, 0xf2, 0x81, 0xff, 0x11, 0x9e, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0x4a, 0xb0, 0xc6, 0x79, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BaseClient is the client API for Base service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BaseClient interface {
	Create(ctx context.Context, in *CreateBaseRequest, opts ...grpc.CallOption) (*CreateBaseReply, error)
	Get(ctx context.Context, in *proto1.GetRequest, opts ...grpc.CallOption) (*GetBaseReply, error)
	List(ctx context.Context, in *proto1.ListRequest, opts ...grpc.CallOption) (*ListBaseReply, error)
	Update(ctx context.Context, in *UpdateBaseRequest, opts ...grpc.CallOption) (*UpdateBaseReply, error)
	Delete(ctx context.Context, in *proto1.DeleteRequest, opts ...grpc.CallOption) (*proto1.EmptyMsg, error)
}

type baseClient struct {
	cc *grpc.ClientConn
}

func NewBaseClient(cc *grpc.ClientConn) BaseClient {
	return &baseClient{cc}
}

func (c *baseClient) Create(ctx context.Context, in *CreateBaseRequest, opts ...grpc.CallOption) (*CreateBaseReply, error) {
	out := new(CreateBaseReply)
	err := c.cc.Invoke(ctx, "/pb.Base/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) Get(ctx context.Context, in *proto1.GetRequest, opts ...grpc.CallOption) (*GetBaseReply, error) {
	out := new(GetBaseReply)
	err := c.cc.Invoke(ctx, "/pb.Base/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) List(ctx context.Context, in *proto1.ListRequest, opts ...grpc.CallOption) (*ListBaseReply, error) {
	out := new(ListBaseReply)
	err := c.cc.Invoke(ctx, "/pb.Base/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) Update(ctx context.Context, in *UpdateBaseRequest, opts ...grpc.CallOption) (*UpdateBaseReply, error) {
	out := new(UpdateBaseReply)
	err := c.cc.Invoke(ctx, "/pb.Base/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) Delete(ctx context.Context, in *proto1.DeleteRequest, opts ...grpc.CallOption) (*proto1.EmptyMsg, error) {
	out := new(proto1.EmptyMsg)
	err := c.cc.Invoke(ctx, "/pb.Base/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseServer is the server API for Base service.
type BaseServer interface {
	Create(context.Context, *CreateBaseRequest) (*CreateBaseReply, error)
	Get(context.Context, *proto1.GetRequest) (*GetBaseReply, error)
	List(context.Context, *proto1.ListRequest) (*ListBaseReply, error)
	Update(context.Context, *UpdateBaseRequest) (*UpdateBaseReply, error)
	Delete(context.Context, *proto1.DeleteRequest) (*proto1.EmptyMsg, error)
}

// UnimplementedBaseServer can be embedded to have forward compatible implementations.
type UnimplementedBaseServer struct {
}

func (*UnimplementedBaseServer) Create(ctx context.Context, req *CreateBaseRequest) (*CreateBaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBaseServer) Get(ctx context.Context, req *proto1.GetRequest) (*GetBaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBaseServer) List(ctx context.Context, req *proto1.ListRequest) (*ListBaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBaseServer) Update(ctx context.Context, req *UpdateBaseRequest) (*UpdateBaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBaseServer) Delete(ctx context.Context, req *proto1.DeleteRequest) (*proto1.EmptyMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBaseServer(s *grpc.Server, srv BaseServer) {
	s.RegisterService(&_Base_serviceDesc, srv)
}

func _Base_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Base/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).Create(ctx, req.(*CreateBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Base/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).Get(ctx, req.(*proto1.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Base/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).List(ctx, req.(*proto1.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Base/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).Update(ctx, req.(*UpdateBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Base/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).Delete(ctx, req.(*proto1.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Base_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Base",
	HandlerType: (*BaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Base_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Base_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Base_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Base_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Base_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/pb/base.proto",
}
