// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/pb/column.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/mazti/restless/shared/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateColumnRequest struct {
	Table                string      `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Default              string      `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	TypeOption           *TypeOption `protobuf:"bytes,5,opt,name=typeOption,proto3" json:"typeOption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateColumnRequest) Reset()         { *m = CreateColumnRequest{} }
func (m *CreateColumnRequest) String() string { return proto.CompactTextString(m) }
func (*CreateColumnRequest) ProtoMessage()    {}
func (*CreateColumnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c412b54bd82ef251, []int{0}
}

func (m *CreateColumnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateColumnRequest.Unmarshal(m, b)
}
func (m *CreateColumnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateColumnRequest.Marshal(b, m, deterministic)
}
func (m *CreateColumnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateColumnRequest.Merge(m, src)
}
func (m *CreateColumnRequest) XXX_Size() int {
	return xxx_messageInfo_CreateColumnRequest.Size(m)
}
func (m *CreateColumnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateColumnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateColumnRequest proto.InternalMessageInfo

func (m *CreateColumnRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *CreateColumnRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateColumnRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateColumnRequest) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *CreateColumnRequest) GetTypeOption() *TypeOption {
	if m != nil {
		return m.TypeOption
	}
	return nil
}

type CreateColumnReply struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Default              string      `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	TypeOption           *TypeOption `protobuf:"bytes,5,opt,name=typeOption,proto3" json:"typeOption,omitempty"`
	CreatedAt            int64       `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64       `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateColumnReply) Reset()         { *m = CreateColumnReply{} }
func (m *CreateColumnReply) String() string { return proto.CompactTextString(m) }
func (*CreateColumnReply) ProtoMessage()    {}
func (*CreateColumnReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c412b54bd82ef251, []int{1}
}

func (m *CreateColumnReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateColumnReply.Unmarshal(m, b)
}
func (m *CreateColumnReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateColumnReply.Marshal(b, m, deterministic)
}
func (m *CreateColumnReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateColumnReply.Merge(m, src)
}
func (m *CreateColumnReply) XXX_Size() int {
	return xxx_messageInfo_CreateColumnReply.Size(m)
}
func (m *CreateColumnReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateColumnReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateColumnReply proto.InternalMessageInfo

func (m *CreateColumnReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateColumnReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateColumnReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateColumnReply) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *CreateColumnReply) GetTypeOption() *TypeOption {
	if m != nil {
		return m.TypeOption
	}
	return nil
}

func (m *CreateColumnReply) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CreateColumnReply) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type UpdateColumnRequest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Table                string      `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string      `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Default              string      `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	TypeOption           *TypeOption `protobuf:"bytes,6,opt,name=typeOption,proto3" json:"typeOption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateColumnRequest) Reset()         { *m = UpdateColumnRequest{} }
func (m *UpdateColumnRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateColumnRequest) ProtoMessage()    {}
func (*UpdateColumnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c412b54bd82ef251, []int{2}
}

func (m *UpdateColumnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateColumnRequest.Unmarshal(m, b)
}
func (m *UpdateColumnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateColumnRequest.Marshal(b, m, deterministic)
}
func (m *UpdateColumnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateColumnRequest.Merge(m, src)
}
func (m *UpdateColumnRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateColumnRequest.Size(m)
}
func (m *UpdateColumnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateColumnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateColumnRequest proto.InternalMessageInfo

func (m *UpdateColumnRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateColumnRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *UpdateColumnRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateColumnRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateColumnRequest) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *UpdateColumnRequest) GetTypeOption() *TypeOption {
	if m != nil {
		return m.TypeOption
	}
	return nil
}

type UpdateColumnReply struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Default              string      `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	TypeOption           *TypeOption `protobuf:"bytes,5,opt,name=typeOption,proto3" json:"typeOption,omitempty"`
	CreatedAt            int64       `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64       `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateColumnReply) Reset()         { *m = UpdateColumnReply{} }
func (m *UpdateColumnReply) String() string { return proto.CompactTextString(m) }
func (*UpdateColumnReply) ProtoMessage()    {}
func (*UpdateColumnReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c412b54bd82ef251, []int{3}
}

func (m *UpdateColumnReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateColumnReply.Unmarshal(m, b)
}
func (m *UpdateColumnReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateColumnReply.Marshal(b, m, deterministic)
}
func (m *UpdateColumnReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateColumnReply.Merge(m, src)
}
func (m *UpdateColumnReply) XXX_Size() int {
	return xxx_messageInfo_UpdateColumnReply.Size(m)
}
func (m *UpdateColumnReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateColumnReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateColumnReply proto.InternalMessageInfo

func (m *UpdateColumnReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateColumnReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateColumnReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateColumnReply) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *UpdateColumnReply) GetTypeOption() *TypeOption {
	if m != nil {
		return m.TypeOption
	}
	return nil
}

func (m *UpdateColumnReply) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UpdateColumnReply) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type TypeOption struct {
	Format               string   `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Precision            string   `protobuf:"bytes,2,opt,name=precision,proto3" json:"precision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeOption) Reset()         { *m = TypeOption{} }
func (m *TypeOption) String() string { return proto.CompactTextString(m) }
func (*TypeOption) ProtoMessage()    {}
func (*TypeOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_c412b54bd82ef251, []int{4}
}

func (m *TypeOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeOption.Unmarshal(m, b)
}
func (m *TypeOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeOption.Marshal(b, m, deterministic)
}
func (m *TypeOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeOption.Merge(m, src)
}
func (m *TypeOption) XXX_Size() int {
	return xxx_messageInfo_TypeOption.Size(m)
}
func (m *TypeOption) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeOption.DiscardUnknown(m)
}

var xxx_messageInfo_TypeOption proto.InternalMessageInfo

func (m *TypeOption) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *TypeOption) GetPrecision() string {
	if m != nil {
		return m.Precision
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateColumnRequest)(nil), "pb.CreateColumnRequest")
	proto.RegisterType((*CreateColumnReply)(nil), "pb.CreateColumnReply")
	proto.RegisterType((*UpdateColumnRequest)(nil), "pb.UpdateColumnRequest")
	proto.RegisterType((*UpdateColumnReply)(nil), "pb.UpdateColumnReply")
	proto.RegisterType((*TypeOption)(nil), "pb.TypeOption")
}

func init() { proto.RegisterFile("base/pb/column.proto", fileDescriptor_c412b54bd82ef251) }

var fileDescriptor_c412b54bd82ef251 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0xc4, 0x55, 0x06, 0x14, 0x60, 0xeb, 0x82, 0x89, 0x8a, 0x88, 0x7c, 0x8a, 0x7a,
	0xf0, 0x4a, 0xe9, 0x8d, 0x5b, 0x29, 0x88, 0x13, 0x42, 0x8a, 0xca, 0x81, 0x13, 0x5a, 0xc7, 0xd3,
	0x74, 0x25, 0xdb, 0xbb, 0x78, 0xc7, 0x87, 0x50, 0xf5, 0xd2, 0x5f, 0xe0, 0xcc, 0x27, 0xf0, 0x35,
	0xfd, 0x05, 0x3e, 0x04, 0x79, 0xd7, 0x4e, 0x49, 0x6b, 0x21, 0x4e, 0x1c, 0xb8, 0xed, 0xbc, 0x19,
	0x3f, 0xbf, 0xb7, 0x6f, 0x77, 0x21, 0x4c, 0x85, 0x41, 0xae, 0x53, 0xbe, 0x52, 0x79, 0x5d, 0x94,
	0x89, 0xae, 0x14, 0x29, 0xe6, 0xeb, 0x74, 0x7a, 0xb8, 0x56, 0x6a, 0x9d, 0x23, 0x17, 0x5a, 0x72,
	0x51, 0x96, 0x8a, 0x04, 0x49, 0x55, 0x1a, 0x37, 0x31, 0x3d, 0x5e, 0x4b, 0xba, 0xa8, 0xd3, 0x64,
	0xa5, 0x0a, 0x5e, 0x88, 0xaf, 0x24, 0x79, 0x85, 0x86, 0x72, 0x34, 0x86, 0x9b, 0x0b, 0x51, 0x61,
	0xc6, 0xed, 0x5c, 0x5b, 0xb8, 0x8f, 0xe2, 0xef, 0x1e, 0xec, 0x9f, 0x56, 0x28, 0x08, 0x4f, 0xed,
	0xdf, 0x96, 0xf8, 0xa5, 0x46, 0x43, 0x2c, 0x84, 0x11, 0x89, 0x34, 0xc7, 0xc8, 0x9b, 0x79, 0xf3,
	0xf1, 0xd2, 0x15, 0x8c, 0xc1, 0xb0, 0x14, 0x05, 0x46, 0xbe, 0x05, 0xed, 0xba, 0xc1, 0x68, 0xa3,
	0x31, 0x1a, 0x38, 0xac, 0x59, 0xb3, 0x08, 0xf6, 0x32, 0x3c, 0x17, 0x75, 0x4e, 0xd1, 0xd0, 0xc2,
	0x5d, 0xc9, 0x12, 0x80, 0x66, 0xe2, 0x83, 0x6e, 0x94, 0x47, 0xa3, 0x99, 0x37, 0x7f, 0xb0, 0x98,
	0x24, 0x3a, 0x4d, 0xce, 0xb6, 0xe8, 0xf2, 0xb7, 0x89, 0xf8, 0xc6, 0x83, 0x27, 0xbb, 0xfa, 0x74,
	0xbe, 0x61, 0x13, 0xf0, 0x65, 0xd6, 0x4a, 0xf3, 0x65, 0xf6, 0xef, 0x75, 0xb1, 0x17, 0x00, 0x2b,
	0x2b, 0x2b, 0xfb, 0x2c, 0x28, 0x0a, 0x66, 0xde, 0x7c, 0xb0, 0x1c, 0xb7, 0xc8, 0x09, 0x35, 0xed,
	0x5a, 0x67, 0x5d, 0x7b, 0xcf, 0xb5, 0x5b, 0xe4, 0x84, 0xe2, 0x1f, 0x1e, 0xec, 0x7f, 0xb4, 0xd5,
	0xee, 0xae, 0xdf, 0xf5, 0xb5, 0x4d, 0xc1, 0xef, 0x4b, 0x61, 0xd0, 0xe3, 0x76, 0xd8, 0xef, 0x76,
	0xf4, 0x27, 0xb7, 0xc1, 0x5f, 0xa5, 0xb0, 0xab, 0xf7, 0x7f, 0x48, 0xe1, 0x35, 0xc0, 0x2d, 0x2f,
	0x7b, 0x0a, 0xc1, 0xb9, 0xaa, 0x0a, 0x41, 0xad, 0xa3, 0xb6, 0x62, 0x87, 0x30, 0xd6, 0x15, 0xae,
	0xa4, 0x69, 0x24, 0x39, 0x6b, 0xb7, 0xc0, 0xe2, 0xda, 0x87, 0xc0, 0xed, 0x09, 0x3b, 0x83, 0xc0,
	0x9d, 0x54, 0xf6, 0xac, 0x91, 0xdc, 0x73, 0xab, 0xa6, 0x07, 0xf7, 0x1b, 0x3a, 0xdf, 0xc4, 0xd3,
	0xeb, 0x9b, 0x9f, 0xdf, 0xfc, 0x30, 0x7e, 0xd4, 0x5e, 0x79, 0x7e, 0x69, 0x83, 0xbe, 0x7a, 0xe5,
	0x1d, 0xb1, 0x4f, 0x10, 0xb8, 0x9d, 0x77, 0xac, 0x3d, 0xa7, 0xc6, 0xb1, 0xde, 0x8b, 0x27, 0x7e,
	0x69, 0x59, 0x9f, 0x2f, 0xc2, 0x3b, 0xac, 0xfc, 0x52, 0x66, 0x96, 0xfa, 0x1d, 0x04, 0x6f, 0x30,
	0x47, 0x42, 0x76, 0x90, 0xb4, 0x8f, 0x82, 0xab, 0x3b, 0xe2, 0xc7, 0x1d, 0xfc, 0xb6, 0xd0, 0xb4,
	0x79, 0x6f, 0xd6, 0x71, 0x68, 0x39, 0x27, 0x47, 0x0f, 0xb7, 0x9c, 0x32, 0xbb, 0x4a, 0x03, 0xfb,
	0x96, 0x1c, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x74, 0xc0, 0x49, 0x26, 0xba, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ColumnClient is the client API for Column service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ColumnClient interface {
	Create(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*CreateColumnReply, error)
	Update(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*UpdateColumnReply, error)
	Delete(ctx context.Context, in *proto1.DeleteRequest, opts ...grpc.CallOption) (*proto1.EmptyMsg, error)
}

type columnClient struct {
	cc *grpc.ClientConn
}

func NewColumnClient(cc *grpc.ClientConn) ColumnClient {
	return &columnClient{cc}
}

func (c *columnClient) Create(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*CreateColumnReply, error) {
	out := new(CreateColumnReply)
	err := c.cc.Invoke(ctx, "/pb.Column/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *columnClient) Update(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*UpdateColumnReply, error) {
	out := new(UpdateColumnReply)
	err := c.cc.Invoke(ctx, "/pb.Column/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *columnClient) Delete(ctx context.Context, in *proto1.DeleteRequest, opts ...grpc.CallOption) (*proto1.EmptyMsg, error) {
	out := new(proto1.EmptyMsg)
	err := c.cc.Invoke(ctx, "/pb.Column/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColumnServer is the server API for Column service.
type ColumnServer interface {
	Create(context.Context, *CreateColumnRequest) (*CreateColumnReply, error)
	Update(context.Context, *UpdateColumnRequest) (*UpdateColumnReply, error)
	Delete(context.Context, *proto1.DeleteRequest) (*proto1.EmptyMsg, error)
}

// UnimplementedColumnServer can be embedded to have forward compatible implementations.
type UnimplementedColumnServer struct {
}

func (*UnimplementedColumnServer) Create(ctx context.Context, req *CreateColumnRequest) (*CreateColumnReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedColumnServer) Update(ctx context.Context, req *UpdateColumnRequest) (*UpdateColumnReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedColumnServer) Delete(ctx context.Context, req *proto1.DeleteRequest) (*proto1.EmptyMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterColumnServer(s *grpc.Server, srv ColumnServer) {
	s.RegisterService(&_Column_serviceDesc, srv)
}

func _Column_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Column/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnServer).Create(ctx, req.(*CreateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Column_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Column/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnServer).Update(ctx, req.(*UpdateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Column_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColumnServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Column/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColumnServer).Delete(ctx, req.(*proto1.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Column_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Column",
	HandlerType: (*ColumnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Column_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Column_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Column_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/pb/column.proto",
}
