// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared/shared.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMsg) Reset()         { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()    {}
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9301c8e954a55bc6, []int{0}
}

func (m *EmptyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMsg.Unmarshal(m, b)
}
func (m *EmptyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMsg.Marshal(b, m, deterministic)
}
func (m *EmptyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMsg.Merge(m, src)
}
func (m *EmptyMsg) XXX_Size() int {
	return xxx_messageInfo_EmptyMsg.Size(m)
}
func (m *EmptyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMsg proto.InternalMessageInfo

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9301c8e954a55bc6, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9301c8e954a55bc6, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9301c8e954a55bc6, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListMetadata struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Total                int64    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMetadata) Reset()         { *m = ListMetadata{} }
func (m *ListMetadata) String() string { return proto.CompactTextString(m) }
func (*ListMetadata) ProtoMessage()    {}
func (*ListMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9301c8e954a55bc6, []int{4}
}

func (m *ListMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMetadata.Unmarshal(m, b)
}
func (m *ListMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMetadata.Marshal(b, m, deterministic)
}
func (m *ListMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMetadata.Merge(m, src)
}
func (m *ListMetadata) XXX_Size() int {
	return xxx_messageInfo_ListMetadata.Size(m)
}
func (m *ListMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ListMetadata proto.InternalMessageInfo

func (m *ListMetadata) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListMetadata) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListMetadata) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListMetadata) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyMsg)(nil), "shared.EmptyMsg")
	proto.RegisterType((*GetRequest)(nil), "shared.GetRequest")
	proto.RegisterType((*ListRequest)(nil), "shared.ListRequest")
	proto.RegisterType((*DeleteRequest)(nil), "shared.DeleteRequest")
	proto.RegisterType((*ListMetadata)(nil), "shared.ListMetadata")
}

func init() { proto.RegisterFile("shared/shared.proto", fileDescriptor_9301c8e954a55bc6) }

var fileDescriptor_9301c8e954a55bc6 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xce, 0x48, 0x2c,
	0x4a, 0x4d, 0xd1, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x12,
	0x17, 0x17, 0x87, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x6f, 0x71, 0xba, 0x92, 0x0c, 0x17, 0x97, 0x7b,
	0x6a, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x92, 0x35, 0x17, 0xb7, 0x4f, 0x66, 0x31,
	0x5c, 0x5a, 0x84, 0x8b, 0x35, 0x27, 0x33, 0x37, 0xb3, 0x04, 0xac, 0x82, 0x35, 0x08, 0xc2, 0x11,
	0x12, 0xe3, 0x62, 0xcb, 0x4f, 0x4b, 0x2b, 0x4e, 0x2d, 0x91, 0x60, 0x02, 0x0b, 0x43, 0x79, 0x4a,
	0xf2, 0x5c, 0xbc, 0x2e, 0xa9, 0x39, 0xa9, 0x25, 0xa9, 0xb8, 0x4c, 0xcf, 0xe0, 0xe2, 0x01, 0x99,
	0xee, 0x9b, 0x5a, 0x92, 0x98, 0x92, 0x58, 0x92, 0x08, 0x32, 0x3e, 0x39, 0xbf, 0x34, 0x0f, 0x6e,
	0x3c, 0x98, 0x83, 0xb0, 0x94, 0x09, 0xbb, 0xa5, 0xcc, 0xc8, 0x96, 0x82, 0x54, 0x97, 0xe4, 0x97,
	0x24, 0xe6, 0x48, 0xb0, 0x28, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x38, 0x49, 0x6c, 0xe0, 0x00, 0x30,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x03, 0x40, 0x8c, 0xdb, 0x17, 0x01, 0x00, 0x00,
}
