// Code generated by entc, DO NOT EDIT.

package meta

import (
	"time"

	"github.com/mazti/restless/newmeta/ent/schema"
)

const (
	// Label holds the string label denoting the meta type in the database.
	Label = "meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBase holds the string denoting the base vertex property in the database.
	FieldBase = "base"
	// FieldSchema holds the string denoting the schema vertex property in the database.
	FieldSchema = "schema"
	// FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at"

	// Table holds the table name of the meta in the database.
	Table = "meta"
)

// Columns holds all SQL columns are meta fields.
var Columns = []string{
	FieldID,
	FieldBase,
	FieldSchema,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	fields = schema.Meta{}.Fields()

	// descCreatedAt is the schema descriptor for created_at field.
	descCreatedAt = fields[2].Descriptor()
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt = descCreatedAt.Default.(func() time.Time)

	// descUpdatedAt is the schema descriptor for updated_at field.
	descUpdatedAt = fields[3].Descriptor()
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt = descUpdatedAt.Default.(func() time.Time)
)
