// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// MetaSchemasColumns holds the columns for the "meta_schemas" table.
	MetaSchemasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "base", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// MetaSchemasTable holds the schema information for the "meta_schemas" table.
	MetaSchemasTable = &schema.Table{
		Name:        "meta_schemas",
		Columns:     MetaSchemasColumns,
		PrimaryKey:  []*schema.Column{MetaSchemasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MetaSchemasTable,
	}
)

func init() {
}
