// Code generated by entc, DO NOT EDIT.

package metatable

import (
	"time"

	"github.com/mazti/restless/base/ent/schema"
)

const (
	// Label holds the string label denoting the metatable type in the database.
	Label = "meta_table"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at vertex property in the database.
	FieldDeletedAt = "deleted_at"

	// Table holds the table name of the metatable in the database.
	Table = "meta_tables"
	// SchemaTable is the table the holds the schema relation/edge.
	SchemaTable = "meta_tables"
	// SchemaInverseTable is the table name for the MetaSchema entity.
	// It exists in this package in order to avoid circular dependency with the "metaschema" package.
	SchemaInverseTable = "meta_schemas"
	// SchemaColumn is the table column denoting the schema relation/edge.
	SchemaColumn = "schema_id"
	// ColumnsTable is the table the holds the columns relation/edge.
	ColumnsTable = "meta_columns"
	// ColumnsInverseTable is the table name for the MetaColumn entity.
	// It exists in this package in order to avoid circular dependency with the "metacolumn" package.
	ColumnsInverseTable = "meta_columns"
	// ColumnsColumn is the table column denoting the columns relation/edge.
	ColumnsColumn = "table_id"
)

// Columns holds all SQL columns are metatable fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

var (
	fields = schema.MetaTable{}.Fields()

	// descCreatedAt is the schema descriptor for created_at field.
	descCreatedAt = fields[1].Descriptor()
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt = descCreatedAt.Default.(func() time.Time)

	// descUpdatedAt is the schema descriptor for updated_at field.
	descUpdatedAt = fields[2].Descriptor()
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt = descUpdatedAt.Default.(func() time.Time)
)
